### PR TITLE
Json identity info deserialization

### PR DESCRIPTION
**Pull request by buehner**
We are currently using the `@JsonIdentityInfo` annotation to serialize only the IDs of related objects (e.g. the groups of a user will be serialized by Jackson as an array of IDs, but not as complete objects.)

This PR handles the deserialization, i.e. the other direction by implementing
```Java
public class UserGroupIdResolver extends SimpleObjectIdResolver
```
and using this implementation in the `resolver` property of the `@JsonIdentityInfo` annotation.

Example: If a new User should be created, it is sufficient to POST an array of (existing) group IDs the user belongs to (in the `userGroups` property of the user object).

**Important note:** The current implementation only sets the ID value on a "new" UserGroup dummy object, which is enough information for Hibernate to persist the correct relation (in the join table). If we want access to full group objects, additional implementations are necessary (i suggest a follow up PR). E.g. the "load" method of the hibernate API could be a good choice here.

### CODE REVIEW

**Comment by buehner** [comment]
I added two commits that add missing ID resolvers for `Map` and `Layer`

**Comment by buehner** [comment]
I added an ID resolver for `Layer` in the last commit

**Comment by marcjansen** [comment]
Is this ready for review?

**Comment by buehner** [comment]
Yes

**Comment by dnlkoch** [comment]
LGTM!

**Comment by KaiVolland** [comment]
Cool stuff. LGTM.

**Comment by weskamm** [comment]
:+1:

**Comment by KaiVolland** [comment]
@buehner plz merge

**Pull request merged**
