### PR TITLE
Module modelling [-- WIP --]

### PR DESCRIPTION
**Pull request by KaiVolland**
Dont merge yet!

Feedack very welcome.

### CODE REVIEW

**Comment by buehner** [comment]
@KaiVolland Thanks for your contribution and granting your repo. I added some commits. I think you can merge after a review of my commits.

**Comment by marcjansen** [comment]
`<pronounciation class="csgo/russian">`nice knife`</pronounciation>`

I like this a LOT!

**Comment by KaiVolland** [comment]
:hocho:

**Pull request merged**
