### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by buehner**
I made some cleanup and updated the versions of dependencies.

Please review and merge if travis is happy.

### CODE REVIEW

**Comment by marcjansen** [comment]
This looks great, @buehner.

Since travis is hanging at the moment, you may merge at your own will. I am confident this doesn't break anything.

**Comment by chrismayer** [comment]
Thanks for this @buehner.
Is it an option to declare the versions with placeholders, so we always get the latest bugfix for example? OR do you prefer setting the version manually? Maybe you will have a look at this (if not known already) http://stackoverflow.com/a/1172371

**Comment by marcjansen** [comment]
Plus one for version ranges.

**Comment by marcjansen** [comment]
The failing builds actually hint something is wrong and are not due to downtime of travis, I guess.

**Comment by buehner** [comment]
Thx for the hint @chrismayer , i will have a look at it.

The build fails on Java 7 as it was not very clever to use 1.8 for the ${jdk.version} property value in the pom.xml.

I will try to add some fixing commits soon.

**Comment by buehner** [comment]
7eb3730 should fix travis by using profiles for different JDK versions.

I also experimented a bit with the version ranges suggested by @chrismayer .
But they did not always behave as expected.

For example i used the range [4.0.0,5.0.0) for hibernate. According to the docs this should always resolve to the latest 4.x.x version, i.e. 4.0.0 <= x < 5.0.0

Unfortunately this resolves to 5.0.0.CR1, which lets the DAO tests fail.

I will have a look at this later. Maybe the the maven versions plugin is a more stable solution: http://www.mojohaus.org/versions-maven-plugin/

As travis is happy now, it would be great if someone could merge!

**Comment by buehner** [comment]
I pushed one more commit (120821e) that will enable the build of javadocs on travis. This is important as there were changes between Java 1.7 and 1.8 (Xdoclint)

**Comment by marcjansen** [comment]
Nice!

**Pull request merged**
