### PR TITLE
Model refactoring

### PR DESCRIPTION
**Pull request by buehner**
This PR mainly contains a major refactoring of the models as we discussed in our codesprint. Some old models have been removed, but will be merged with the new models and reintroduced in a next step.

### CODE REVIEW

**Comment by marcjansen** [comment]
Missing the methods `hashCode()`, `equals(Object)` & `toString()` for all (?) the models

**Comment by KaiVolland** [comment]
I like! Testes are fine. Please merge. :dancers:

**Comment by marcjansen** [comment]
:+1: (once my comment is adressed)

**Comment by marcjansen** [comment]
Nice!

**Pull request merged**
