### PR TITLE
Changes registration methods from private/protected to public

### PR DESCRIPTION
**Pull request by KaiVolland**
I need to access theses methods from outside. Alternatives welcome.

### CODE REVIEW

**Comment by marcjansen** [comment]
Commit history doesn't look well. We can sort it out together.

**Comment by KaiVolland** [comment]
I'm more interested in feedback to the code. But if this is ok we can cleanup history...

**Comment by chrismayer** [comment]
Hi @KaiVolland, do you have more information waht are the reasons to change the visibilitiy to public?

**Comment by KaiVolland** [comment]
It's projectspecific stuff where i have to create users from outside of the userservice.
Therefore i need to get a token and send a registration mail.

**Comment by chrismayer** [comment]
OK, then you can change visibility as you did or you can introduce public wrapper methods.

**Comment by buehner** [comment]
Both methods are called from the `sendRegistrationActivationMail` in the `RegistrationTokenService`.

If you want to send a registration activation mail. Wouldn't that be a method you could use?

**Comment by buehner** [comment]
Maybe it makes sense to refactor the `sendRegistrationActivationMail` method to accept a mail message (instead of always using the `registrationMailMessageTemplate`)!?

**Comment by KaiVolland** [comment]
No cause this method sends an email itself. I need just the url and the token to put it in my projectspecific mail.

Are there any security-concerns etc. with my suggested changes?
If yes, a refactoring of the `RegistrationTokenService` would be ok for me.
If no, i would just like to see this merged.

**Comment by buehner** [comment]
If you want a projectspecific mail content, then please change the `sendRegistrationActivationMail` method to accept a `SimpleMailMessage` object with your specific mail content. The current implementation always uses the injected `registrationMailMessageTemplate`.

I am not sure if we really want to make the `getValidTokenForUser` method public. For example, the `buildConcreteInstance` method is called there (which is an abstract method without implementation) that has to be implemented by subclasses (like the `RegistrationTokenService` does).

**Comment by KaiVolland** [comment]
I refactored the Service. So just `createRegistrationActivationURI` is public now. It now receives an user instead of a token.

**Comment by buehner** [comment]
:+1: merge if you want

**Comment by KaiVolland** [comment]
Thanks

**Comment by marcjansen** [comment]
Nice discussion here, everyone 👏👏👏

**Pull request merged**
